travis:
  secure:
    BINSTAR_TOKEN: u0Z8jlsQyEIa+wbWObndKGzmTzpqH6W3//IiagxyqxQqmObXJ2NRS5kSfT2r2bcCsaZipqDUkWqGiStPlRJ7sBLjJ9MdMNJV4d2LM781BwFrPJ0IzRRaYJMvpHDfZouY3KxnGOMn4KR+6nGOjtkDkGXhCeo6WAKiD8CJy5N3rGd05zgr2UFVq5DbwykTxtVQ6+OoiUbOUKf0E6/pSTj7Gbo+vSOnEjIw94fHxOITG8ct+v9wv2spKzABSPeNOlT+83kIKVjbeIyvD7/O21Boa6lwn9T0JxNHSwEtCssIJZdatmU831f7/h+HgboPUN+w19cyj/1v/cKmga1uN9fK/5xCXi9s9FXD4bZ6KZzNplMDh5eNFNR1RLjuJvwv/dkmvgDtYtMWlJ5Ctxl24XeeJSaoZFuq7FjTL5fytTSbOwIb7waSekdeeecR4Vo1iZHnYFqrfHUxel+sGBLHKDuXb9o+lNT9q6tEFbOr3/1SII3Hhnd+ubLGUoBgZxKmuMwOE2pCvVQyHJWJTE9V97TI0acEU/UGfDCY6Txj48YwDWq27pqtgvAshG4lBfI0g55uFoQqnjAMrdu72bRtxnge8B0nZn70gwKfUQz3TWpUcclhUqlNC9LyyjO9CqMuMymgHjrBp/STVDWGJssDSEzui6ZmxI48L0In7EHcR8qcf7o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
